package masque

// Performance regression tests for the MASQUE auth layer.
//
// Run:
//   go test -race -count=1 -run TestPerf ./protocol/masque/...
//   go test -bench=. -benchmem -run=^$ ./protocol/masque/...
//
// T1  HMAC key precomputation — ValidateAuthHeaderCached / NewHMACKeyCache

import (
	"net/http"
	"testing"
)

var testMasqueUUID = [16]byte{0xAA, 0xBB, 0xCC, 0xDD, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

// ── T1: MASQUE HMAC key precomputation ───────────────────────────────────────

// TestNewHMACKeyCache_BuildsCorrectly verifies NewHMACKeyCache returns a
// non-nil cache containing the expected UUID entry.
//
// RED: NewHMACKeyCache panics (not implemented).
func TestNewHMACKeyCache_BuildsCorrectly(t *testing.T) {
	uuids := [][16]byte{testMasqueUUID}
	cache := NewHMACKeyCache(uuids)
	if cache == nil {
		t.Fatal("NewHMACKeyCache returned nil")
	}
	if _, ok := cache[testMasqueUUID]; !ok {
		t.Fatal("cache does not contain the registered UUID")
	}
}

// TestValidateAuthHeaderCached_AcceptsValidToken verifies that a token
// generated by GenerateAuthHeader is accepted by the cached validator.
//
// RED: ValidateAuthHeaderCached panics (not implemented).
func TestValidateAuthHeaderCached_AcceptsValidToken(t *testing.T) {
	hdr, err := GenerateAuthHeader(testMasqueUUID)
	if err != nil {
		t.Fatalf("GenerateAuthHeader: %v", err)
	}
	cache := NewHMACKeyCache([][16]byte{testMasqueUUID})
	got, err := ValidateAuthHeaderCached(hdr, cache)
	if err != nil {
		t.Fatalf("ValidateAuthHeaderCached: %v", err)
	}
	if got != testMasqueUUID {
		t.Fatalf("UUID mismatch: got %v, want %v", got, testMasqueUUID)
	}
}

// TestValidateAuthHeaderCached_RejectsUnknownUUID verifies an unregistered
// UUID is rejected even with a precomputed cache.
//
// RED: ValidateAuthHeaderCached panics (not implemented).
func TestValidateAuthHeaderCached_RejectsUnknownUUID(t *testing.T) {
	hdr, err := GenerateAuthHeader(testMasqueUUID)
	if err != nil {
		t.Fatalf("GenerateAuthHeader: %v", err)
	}
	otherUUID := [16]byte{0xFF}
	cache := NewHMACKeyCache([][16]byte{otherUUID})
	_, err = ValidateAuthHeaderCached(hdr, cache)
	if err == nil {
		t.Fatal("expected auth error for unknown UUID, got nil")
	}
}

// TestValidateAuthHeaderCached_RejectsMissingHeader verifies an empty header
// is rejected.
//
// RED: ValidateAuthHeaderCached panics (not implemented).
func TestValidateAuthHeaderCached_RejectsMissingHeader(t *testing.T) {
	cache := NewHMACKeyCache([][16]byte{testMasqueUUID})
	_, err := ValidateAuthHeaderCached(http.Header{}, cache)
	if err == nil {
		t.Fatal("expected error for missing X-Masque-Auth header")
	}
}

// TestValidateAuthHeaderCached_AllocsReduced asserts that the cached variant
// does not allocate MORE than the uncached baseline, and documents the alloc
// count reduction from eliminating sha256.Sum256 per UUID candidate.
func TestValidateAuthHeaderCached_AllocsReduced(t *testing.T) {
	hdr, _ := GenerateAuthHeader(testMasqueUUID)
	uuids := [][16]byte{testMasqueUUID}
	cache := NewHMACKeyCache(uuids)

	baseline := testing.AllocsPerRun(20, func() {
		_, _ = ValidateAuthHeader(hdr, uuids)
	})
	cached := testing.AllocsPerRun(100, func() {
		_, _ = ValidateAuthHeaderCached(hdr, cache)
	})
	if cached > baseline {
		t.Fatalf("ValidateAuthHeaderCached allocs = %.0f > baseline %.0f (regression)", cached, baseline)
	}
}

// BenchmarkValidateAuthHeader_Baseline documents current alloc cost.
func BenchmarkValidateAuthHeader_Baseline(b *testing.B) {
	hdr, _ := GenerateAuthHeader(testMasqueUUID)
	uuids := [][16]byte{testMasqueUUID}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = ValidateAuthHeader(hdr, uuids)
	}
}

// BenchmarkValidateAuthHeaderCached documents target alloc cost.
//
// RED: panics until Green is implemented.
func BenchmarkValidateAuthHeaderCached(b *testing.B) {
	hdr, _ := GenerateAuthHeader(testMasqueUUID)
	cache := NewHMACKeyCache([][16]byte{testMasqueUUID})
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = ValidateAuthHeaderCached(hdr, cache)
	}
}
